### PR TITLE
Added vanillajs template

### LINKED ISSUE #2: Feature Request: Add HTML, CSS, and JavaScript Support
**Description:**

I would like to request the addition of HTML, CSS, and JavaScript support to the project generated by StartEase.

### PR DESCRIPTION
**Pull request by Toyin5**
Added the vanilla js template
Introduced a new folder structure
Updated the .gitignore to accommodate lock files
Resolves #2

### CODE REVIEW

**Comment by Toyin5** [comment]
@JC-Coder  review pls

**Comment by JC-Coder** [comment]
@Toyin5 
1. your pr should be made against the dev branch 
2. your branch should not be master . you should have a branch indicating the feature you are working on e.g vanilla-js 
3. the template name should not be vanillajs as it is not a standalone . it should be HTML X CSS X JAVASCRIPT  that way users would understand what that option does. 

please review these changes so i can merge

**Comment by Toyin5** [comment]
OK
I will make the required changes
But vanillajs is the same as html/css/javascript 
You should check vite templates https://vitejs.dev/guide/

**Comment by Toyin5** [comment]
I will open a new one for the change

**Pull request closed without merging**
