### PR TITLE
Django support dev

### PR DESCRIPTION
**Pull request by codewitgabi**
- Added support for django and sqlite3.
- Added .env to store secret variables.
- Tested it in the test directory with the My Blog project.
- Tested other frameworks to make sure nothing was broken.

### CODE REVIEW

**Comment by JC-Coder** [comment]
1. there is an issue in your static file -> static/css holds js and css file (fix it ) 
2. you added postgreSQL in prompt when it's not yet available (remove) 
3. in the test file you are meant to name it django not Blog. it's for testing various framework while making the cli feature 
4. cleanup your code and do extra check

**Comment by codewitgabi** [comment]
What name do you suggested I use for the test?

**Comment by JC-Coder** [comment]
You can add an extension to it e.g django-test

**Comment by codewitgabi** [comment]
Ok. I already used django_ if that's ok or I should still change it?

**Comment by JC-Coder** [comment]
please fix your conflicts

**Comment by codewitgabi** [comment]
Merge conflicts have been resolved

**Comment by JC-Coder** [comment]
@codewitgabi 
your django template (css, js , html ) have empty datas. it would be better to add some demo data . take reference from other templates . also there is no mongodb support for django , yet it's showing in the database selection process. kindly fix

**Comment by codewitgabi** [comment]
Ok

**Pull request merged**
